jbs_new_media_assets_composer:
  path: /assetscomposer/{namespace}/{package}/{asset}
  controller: JBSNewMedia\AssetComposerBundle\Controller\AssetComposerController::getAsset
  requirements:
    namespace: '[a-zA-Z_][a-zA-Z0-9_-]*'
    package: '[a-zA-Z_][a-zA-Z0-9_-]*'
    asset: '.+'